apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: cake-delight
type: Opaque
data:
  POSTGRES_USER: Y2F0YWxvZ191c2Vy          # catalog_user
  POSTGRES_PASSWORD: Y2F0YWxvZ19wYXNz      # catalog_pass
  POSTGRES_DB: Y2F0YWxvZ19kYg==            # catalog_db
  DATABASE_URL: cG9zdGdyZXM6Ly9jYXRhbG9nX3VzZXI6Y2F0YWxvZ19wYXNzQGNhdGFsb2ctZGI6NTQzMi9jYXRhbG9nX2Ri

---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: cake-delight
type: Opaque
data:
  POSTGRES_USER: b3JkZXJfdXNlcg==          # order_user
  POSTGRES_PASSWORD: b3JkZXJfcGFzcw==      # order_pass
  POSTGRES_DB: b3JkZXJfZGI=                # order_db
  DATABASE_URL: cG9zdGdyZXM6Ly9vcmRlcl91c2VyOm9yZGVyX3Bhc3NAb3JkZXItZGI6NTQzMi9vcmRlcl9kYg==

---
apiVersion: v1
kind: Secret
metadata:
  name: rating-db-secret
  namespace: cake-delight
type: Opaque
data:
  POSTGRES_USER: cmF0aW5nX3VzZXI=          # rating_user
  POSTGRES_PASSWORD: cmF0aW5nX3Bhc3M=      # rating_pass
  POSTGRES_DB: cmF0aW5nX2Ri                # rating_db
  DATABASE_URL: cG9zdGdyZXM6Ly9yYXRpbmdfdXNlcjpyYXRpbmdfcGFzc0ByYXRpbmctZGI6NTQzMi9yYXRpbmdfZGI=
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-db-secret
  namespace: cake-delight
type: Opaque
data:
  POSTGRES_USER: bm90aWZpY2F0aW9uX3VzZXI=      # notification_user
  POSTGRES_PASSWORD: bm90aWZpY2F0aW9uX3Bhc3M=  # notification_pass
  POSTGRES_DB: bm90aWZpY2F0aW9uX2Ri            # notification_db
  DATABASE_URL: cG9zdGdyZXM6Ly9ub3RpZmljYXRpb25fdXNlcjpub3RpZmljYXRpb25fcGFzc0Bub3RpZmljYXRpb24tZGI6NTQzMi9ub3RpZmljYXRpb25fZGI=

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: cake-delight
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Y2FrZXVzZXI=      # cakeuser
  RABBITMQ_DEFAULT_PASS: Y2FrZXBhc3M=      # cakepass
  RABBITMQ_URL: YW1xcDovL2Nha2V1c2VyOmNha2VwYXNzQHJhYmJpdG1xOjU2NzI=

---
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
  namespace: cake-delight
type: Opaque
data:
  EMAIL_USER: "dmFuLmRpY2tlbnNAZXRoZXJlYWwuZW1haWw="   
  EMAIL_PASS: "NGRKTXVZSEUyeURFakVuUzFR"
  EMAIL_FROM: "b3JkZXJzQGNha2VkZWxpZ2h0LnRlc3Q="