apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cake-delight

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: cake-delight-api-gateway:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 5000
              name: http

          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 2
          #   failureThreshold: 3

          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 20
          #   periodSeconds: 20
          #   timeoutSeconds: 2
          #   failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "250m"