apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cake-delight

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: cake-delight-api-gateway:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 5000
              name: http

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "250m"